server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.jps.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/jps/"
  application:
    name: Judicial Payment Service
    jackson:
      property-naming-strategy: SNAKE_CASE
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${JUDICIAL_PAYMENT_SERVICE_DB_HOST:localhost}:${JUDICIAL_PAYMENT_SERVICE_DB_PORT:5060}/${JUDICIAL_PAYMENT_SERVICE_NAME:judicial-payment-service}${JUDICIAL_PAYMENT_SERVICE_DB_OPTIONS:}
      username: ${JUDICIAL_PAYMENT_SERVICE_USERNAME:hmc}
      password: ${JUDICIAL_PAYMENT_SERVICE_DB_PASSWORD:hmc}
      type: com.zaxxer.hikari.HikariDataSource
    jpa:
      database: postgresql
      show-sql: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            time_zone: UTC
    flyway:
      out-of-order: true
      ignore-missing-migrations: true

azure:
  application-insights:
    instrumentation-key: ${jps.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
