java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    JUDICIAL_PAYMENT_SERVICE_DB_HOST: "{{ .Release.Name }}-postgresql"
    JUDICIAL_PAYMENT_SERVICE_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    JUDICIAL_PAYMENT_SERVICE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
    JUDICIAL_PAYMENT_SERVICE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    JUDICIAL_PAYMENT_SERVICE_DB_OPTIONS: "?stringtype=unspecified"
    JUDICIAL_PAYMENT_SERVICE_DB_PORT: 5432
    RUN_DB_MIGRATION_ON_STARTUP: true
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    LOCATION_API_URL: http://rd-location-ref-api-aat.service.core-compute-aat.internal
    JUDICIAL_USERS_API_URL: http://rd-judicial-api-aat.service.core-compute-aat.internal
    CASEWORKER_API_URL: http://rd-caseworker-ref-api-aat.service.core-compute-aat.internal
  postgresql:
    enabled: true
  keyVaults:
    jps:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: jps-judicial-payment-service-s2s-secret
          alias: JPS_JUDICIAL_PAYMENT_SERVICE_S2S_SECRET
        - name: idam-jps-system-username
          alias: IDAM_JPS_SYSTEM_USERNAME
        - name: idam-jps-system-password
          alias: IDAM_JPS_SYSTEM_PASSWORD
        - name: idam-jps-judicial-payment-service-client-secret
          alias: IDAM_JPS_JUDICIAL_PAYMENT_SERVICE_CLIENT_SECRET
