java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/jps/judicial-payment-service:latest'
  ingressHost: jps-judicial-payment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: jps
#  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    jps:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: judicial-payment-service-POSTGRES-USER
          alias: JUDICIAL_PAYMENT_SERVICE_DB_USERNAME
        - name: judicial-payment-service-POSTGRES-PASS
          alias: JUDICIAL_PAYMENT_SERVICE_DB_PASSWORD
        - name: judicial-payment-service-POSTGRES-HOST
          alias: JUDICIAL_PAYMENT_SERVICE_DB_HOST
        - name: judicial-payment-service-POSTGRES-PORT
          alias: JUDICIAL_PAYMENT_SERVICE_DB_PORT
        - name: judicial-payment-service-POSTGRES-DATABASE
          alias: JUDICIAL_PAYMENT_SERVICE_DB_NAME
        - name: idam-jps-system-username
          alias: IDAM_JPS_SYSTEM_USERNAME
        - name: idam-jps-system-password
          alias: IDAM_JPS_SYSTEM_PASSWORD
        - name: idam-jps-judicial-payment-service-client-secret
          alias: JPS_JUDICIAL_PAYMENT_SERVICE_IDAM_CLIENT_SECRET
        - name: jps-judicial-payment-service-s2s-secret
          alias: IDAM_KEY_JPS_JUDICIAL_PAYMENT_SERVICE
  environment:
    JUDICIAL_PAYMENT_SERVICE_DB_OPTIONS: "?stringtype=unspecified&gssEncMode=disable"
    RUN_DB_MIGRATION_ON_STARTUP: false
    IDAM_OIDC_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    JPS_PAYMENT_SERVUCE_S2S_AUTHORISED_SERVICES: jps_webapp
    HTTP_CLIENT_CONNECTION_TIMEOUT: '10000'
    HTTP_CLIENT_READ_TIMEOUT: '60000'
    HTTP_CLIENT_MAX_TOTAL: '200'
    HTTP_CLIENT_SECONDS_IDLE_CONNECTION: '120'
    HTTP_CLIENT_MAX_CLIENT_PER_ROUTE: '20'
    HTTP_CLIENT_VALIDATE_AFTER_INACTIVITY: '2000'
    LOCATION_API_URL: http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    JUDICIAL_USERS_API_URL: http://rd-judicial-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASEWORKER_API_URL: http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
