spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11:///localhost?stringtype=unspecified
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:${wiremock.server.port:5000}/o
idam:
  api:
    url: http://localhost:${wiremock.server.port:5000}
  s2s-auth:
    url: http://localhost:${wiremock.server.port:5000}/s2s

location:
  api:
    url: http://localhost:${wiremock.server.port:5000}

judicialUsers:
  api:
    url: http://localhost:${wiremock.server.port:5000}

caseworker:
  api:
    url: http://localhost:${wiremock.server.port:5000}
